// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @aipaas/apiKey
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.hash)
    c.string.preencode(state, m.prefix)
    state.end++ // flags are fixed size

    if (m.permissions) c.string.preencode(state, m.permissions)
    if (m.rateLimitRequestsPerMin) c.uint.preencode(state, m.rateLimitRequestsPerMin)
    if (m.rateLimitTokensPerHour) c.uint.preencode(state, m.rateLimitTokensPerHour)
    if (m.lastUsedAt) c.uint.preencode(state, m.lastUsedAt)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags =
      (m.permissions ? 1 : 0) |
      (m.rateLimitRequestsPerMin ? 2 : 0) |
      (m.rateLimitTokensPerHour ? 4 : 0) |
      (m.lastUsedAt ? 8 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.hash)
    c.string.encode(state, m.prefix)
    c.uint8.encode(state, flags)

    if (m.permissions) c.string.encode(state, m.permissions)
    if (m.rateLimitRequestsPerMin) c.uint.encode(state, m.rateLimitRequestsPerMin)
    if (m.rateLimitTokensPerHour) c.uint.encode(state, m.rateLimitTokensPerHour)
    if (m.lastUsedAt) c.uint.encode(state, m.lastUsedAt)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      id: r0,
      name: r1,
      hash: r2,
      prefix: r3,
      permissions: (flags & 1) !== 0 ? c.string.decode(state) : null,
      rateLimitRequestsPerMin: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      rateLimitTokensPerHour: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      lastUsedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      createdAt: c.uint.decode(state),
    }
  },
}

// @aipaas/deployment
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.model)
    c.string.preencode(state, m.status)
    state.end++ // flags are fixed size

    if (m.contextWindow) c.uint.preencode(state, m.contextWindow)
    if (m.temperature) c.float32.preencode(state, m.temperature)
    if (m.maxTokens) c.uint.preencode(state, m.maxTokens)
    c.uint.preencode(state, m.createdAt)
    c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = (m.contextWindow ? 1 : 0) | (m.temperature ? 2 : 0) | (m.maxTokens ? 4 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.model)
    c.string.encode(state, m.status)
    c.uint8.encode(state, flags)

    if (m.contextWindow) c.uint.encode(state, m.contextWindow)
    if (m.temperature) c.float32.encode(state, m.temperature)
    if (m.maxTokens) c.uint.encode(state, m.maxTokens)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      id: r0,
      model: r1,
      status: r2,
      contextWindow: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      temperature: (flags & 2) !== 0 ? c.float32.decode(state) : 0,
      maxTokens: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      createdAt: c.uint.decode(state),
      updatedAt: c.uint.decode(state),
    }
  },
}

// @aipaas/usageRecord
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.keyId)
    c.string.preencode(state, m.model)
    c.uint.preencode(state, m.inputTokens)
    c.uint.preencode(state, m.outputTokens)
    c.uint.preencode(state, m.latencyMs)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.keyId)
    c.string.encode(state, m.model)
    c.uint.encode(state, m.inputTokens)
    c.uint.encode(state, m.outputTokens)
    c.uint.encode(state, m.latencyMs)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.uint.decode(state)
    const r6 = c.uint.decode(state)

    return {
      id: r0,
      keyId: r1,
      model: r2,
      inputTokens: r3,
      outputTokens: r4,
      latencyMs: r5,
      timestamp: r6,
    }
  },
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@aipaas/apiKey':
      return encoding0
    case '@aipaas/deployment':
      return encoding1
    case '@aipaas/usageRecord':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    },
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
