import Hypercore from 'hypercore'
import HyperDB from 'hyperdb'
import type { HyperDB as HyperDBInstance } from 'hyperdb'
// @ts-expect-error — autogenerated JS from hyperdb compiler, no types
import definition from '../../spec/hyperdb/index.js'

export async function createDatabase(storagePath: string): Promise<HyperDBInstance> {
  const core = new Hypercore(storagePath)
  const db = HyperDB.bee(core, definition)
  await db.ready()
  return db
}

export const COLLECTIONS = {
  API_KEYS: '@aipaas/apiKeys',
  DEPLOYMENTS: '@aipaas/deployments',
  USAGE_RECORDS: '@aipaas/usageRecords',
} as const

export const INDEXES = {
  API_KEYS_BY_HASH: '@aipaas/apiKeys-by-hash',
  DEPLOYMENTS_BY_MODEL: '@aipaas/deployments-by-model',
  USAGE_BY_KEY_ID: '@aipaas/usageRecords-by-keyId',
  USAGE_BY_MODEL: '@aipaas/usageRecords-by-model',
} as const
