import Hypercore from 'hypercore'
import HyperDB from 'hyperdb'
import type { HyperDB as HyperDBInstance } from 'hyperdb'
// @ts-expect-error — autogenerated JS from hyperdb compiler, no types
import definition from '../../spec/hyperdb/index'

export interface DatabaseInstance {
  db: HyperDBInstance
  core: Hypercore
}

export async function createDatabase(storagePath: string): Promise<DatabaseInstance> {
  const core = new Hypercore(storagePath)
  const db = HyperDB.bee(core, definition)
  await db.ready()
  return { db, core }
}
