// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const versions = { schema: version, db: 1 }

// '@aipaas/apiKeys' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@aipaas/apiKeys' value encoding
const collection0_enc = getEncoding('@aipaas/apiKey/hyperdb#0')

// '@aipaas/apiKeys' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@aipaas/apiKeys' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@aipaas/apiKeys'
const collection0 = {
  name: '@aipaas/apiKeys',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@aipaas/deployments' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@aipaas/deployments' value encoding
const collection1_enc = getEncoding('@aipaas/deployment/hyperdb#1')

// '@aipaas/deployments' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.id = key[0]
  return record
}
// '@aipaas/deployments' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@aipaas/deployments'
const collection1 = {
  name: '@aipaas/deployments',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@aipaas/usageRecords' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@aipaas/usageRecords' value encoding
const collection2_enc = getEncoding('@aipaas/usageRecord/hyperdb#2')

// '@aipaas/usageRecords' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.id = key[0]
  return record
}
// '@aipaas/usageRecords' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@aipaas/usageRecords'
const collection2 = {
  name: '@aipaas/usageRecords',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@aipaas/apiKeys-by-hash' collection key
const index3_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 3 })

function index3_indexify (record) {
  const a = record.hash
  return a === undefined ? [] : [a]
}

// '@aipaas/apiKeys-by-hash'
const index3 = {
  name: '@aipaas/apiKeys-by-hash',
  version: 1,
  id: 3,
  encodeKey (record) {
    return index3_key.encode(index3_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index3_key.encodeRange({
      gt: gt ? index3_indexify(gt) : null,
      lt: lt ? index3_indexify(lt) : null,
      gte: gte ? index3_indexify(gte) : null,
      lte: lte ? index3_indexify(lte) : null
    })
  },
  encodeValue: (record) => index3.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index3_key.encode([record.hash])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index3)

// '@aipaas/deployments-by-model' collection key
const index4_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 4 })

function index4_indexify (record) {
  const arr = []

  const a0 = record.model
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.id
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@aipaas/deployments-by-model'
const index4 = {
  name: '@aipaas/deployments-by-model',
  version: 1,
  id: 4,
  encodeKey (record) {
    return index4_key.encode(index4_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index4_key.encodeRange({
      gt: gt ? index4_indexify(gt) : null,
      lt: lt ? index4_indexify(lt) : null,
      gte: gte ? index4_indexify(gte) : null,
      lte: lte ? index4_indexify(lte) : null
    })
  },
  encodeValue: (record) => index4.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index4_key.encode([record.model, record.id])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index4)

// '@aipaas/usageRecords-by-keyId' collection key
const index5_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 5 })

function index5_indexify (record) {
  const arr = []

  const a0 = record.keyId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.id
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@aipaas/usageRecords-by-keyId'
const index5 = {
  name: '@aipaas/usageRecords-by-keyId',
  version: 1,
  id: 5,
  encodeKey (record) {
    return index5_key.encode(index5_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index5_key.encodeRange({
      gt: gt ? index5_indexify(gt) : null,
      lt: lt ? index5_indexify(lt) : null,
      gte: gte ? index5_indexify(gte) : null,
      lte: lte ? index5_indexify(lte) : null
    })
  },
  encodeValue: (record) => index5.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index5_key.encode([record.keyId, record.id])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection2.indexes.length,
  collection: collection2
}
collection2.indexes.push(index5)

// '@aipaas/usageRecords-by-model' collection key
const index6_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 6 })

function index6_indexify (record) {
  const arr = []

  const a0 = record.model
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.id
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@aipaas/usageRecords-by-model'
const index6 = {
  name: '@aipaas/usageRecords-by-model',
  version: 1,
  id: 6,
  encodeKey (record) {
    return index6_key.encode(index6_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index6_key.encodeRange({
      gt: gt ? index6_indexify(gt) : null,
      lt: lt ? index6_indexify(lt) : null,
      gte: gte ? index6_indexify(gte) : null,
      lte: lte ? index6_indexify(lte) : null
    })
  },
  encodeValue: (record) => index6.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    return [index6_key.encode([record.model, record.id])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection2.indexes.length,
  collection: collection2
}
collection2.indexes.push(index6)

const collections = [
  collection0,
  collection1,
  collection2
]

const indexes = [
  index3,
  index4,
  index5,
  index6
]

export default { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@aipaas/apiKeys': return collection0
    case '@aipaas/deployments': return collection1
    case '@aipaas/usageRecords': return collection2
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@aipaas/apiKeys-by-hash': return index3
    case '@aipaas/deployments-by-model': return index4
    case '@aipaas/usageRecords-by-keyId': return index5
    case '@aipaas/usageRecords-by-model': return index6
    default: return null
  }
}
