import Hypercore from 'hypercore'
import HyperDB from 'hyperdb'
import type { HyperDB as HyperDBInstance } from 'hyperdb'
import Hyperswarm from 'hyperswarm'
// @ts-expect-error — autogenerated JS from hyperdb compiler, no types
import definition from '../../spec/hyperdb/index'
import type { Logger } from '../logger'

/**
 * Read-only HyperDB replica that replicates from the gateway's core.
 *
 * The gateway serves its Hypercore on a Hyperswarm topic (the core's
 * discoveryKey). This replica joins that topic as a client and syncs
 * incrementally. All writes go through the gateway — this replica
 * will throw on any write attempt.
 */
export class DbReplica {
  private core: Hypercore | null = null
  private dht: { destroy: () => Promise<void> } | null = null
  private swarm: Hyperswarm | null = null
  db: HyperDBInstance | null = null
  private starting = false

  constructor(
    private storagePath: string,
    private dhtBootstrap: Array<{ host: string; port: number }> | undefined,
    private logger: Logger,
  ) {}

  async start(gatewayDbKeyHex: string): Promise<void> {
    if (this.starting) return
    this.starting = true

    const gatewayDbKey = Buffer.from(gatewayDbKeyHex, 'hex')

    this.core = new Hypercore(this.storagePath, gatewayDbKey)
    await this.core.ready()

    this.db = HyperDB.bee(this.core, definition)
    await this.db.ready()

    // Replicate via a separate Hyperswarm that joins the core's discovery key
    const DHT = (await import('hyperdht')).default
    const dht = new DHT({ bootstrap: this.dhtBootstrap, firewalled: false })
    await dht.ready()
    this.dht = dht

    this.swarm = new Hyperswarm({ dht })
    this.swarm.on('connection', (connection) => {
      this.core?.replicate(connection)
    })

    const discovery = this.swarm.join(this.core.discoveryKey, { server: false, client: true })
    await discovery.flushed()

    this.logger.info(
      { dbKey: gatewayDbKeyHex.slice(0, 16), writable: this.core.writable },
      'DB replica connected — replicating from gateway',
    )
  }

  async shutdown(): Promise<void> {
    if (this.swarm) {
      await this.swarm.destroy()
      this.swarm = null
    }
    if (this.db) {
      await this.db.close()
      this.db = null
    }
    if (this.core) {
      await this.core.close()
      this.core = null
    }
    if (this.dht) {
      await this.dht.destroy()
      this.dht = null
    }
  }
}
